### ISSUE TITLE
No "Options" on loading screen.

### ISSUE THREAD

**Issue by IamAlathe** [TheLimePixel/Crop-Block#10]
Just a minor oversight:  Mod Options is available, but the vanilla options button is not.  Usually the first thing I do, even before creating a world, is adjust sound and remap a couple of keys and check for keybind conflicts.  (It makes me crazy not to have my inventory mapped to the tab key.)  There is no way to do this from your loading screen.

**Comment by Mystogrigen** [comment]
![options](https://user-images.githubusercontent.com/30390280/38773252-c8532d40-4015-11e8-9451-686b6c23950f.png)

It's that gear symbol.

**Comment by IamAlathe** [comment]
Ah, so I just missed it.  Thanks!
