### ISSUE TITLE
Game crashed after acquiring a 10/10/10 dirt seed

### ISSUE THREAD

**Issue by tupe12** [TheLimePixel/Crop-Block#11]
[crash-2018-04-15_16.38.32-client.txt](https://github.com/EmosewaPixel/Crop-Block/files/1912857/crash-2018-04-15_16.38.32-client.txt)
After it started raining and I got a 10/10/10 dirt seed, my game crashed.

**Comment by TheLimePixel** [comment]
It's because of your irrigation system, not 10/10/10 dirt seeds. Never the less...

**Comment by tupe12** [comment]
What exactly in the irrigation system broke it? or is it just random bad luck?
