### ISSUE TITLE
Crystal Flux Essence is not able to create Flux Crystal from Redstone Arsenal

### ISSUE THREAD

**Issue by DanBTechnology** [TheLimePixel/Crop-Block#18]
When I look in JEI, I see that I need the Crystal Flux Singularity to complete the final quest, but the Essence that grows Crystal Flux doesn't craft into anything... Tried in all crafting tables still doesn't work.

**Comment by Jepehal** [comment]
I can confirm that this is the case. I assume that the Flux Crystal seeds are custom and the creator just forgot about them, or something like that. Anyway, for the time being, while waiting for an official update I would add a recipe to recipes.zs in the scripts folder with something like this:
```
recipes.addShaped(<redstonearsenal:material:160>,[
[<jaopca:item_essencecrystalflux>,<jaopca:item_essencecrystalflux>,<jaopca:item_essencecrystalflux>],
[<jaopca:item_essencecrystalflux>,<jaopca:item_essencecrystalflux>,<jaopca:item_essencecrystalflux>],
[<jaopca:item_essencecrystalflux>,<jaopca:item_essencecrystalflux>,<jaopca:item_essencecrystalflux>]
]);
```

**Comment by DanBTechnology** [comment]
Ok thanks so much!
Edit: Nvm I just saw where you said it was! Thank you!
