### ISSUE TITLE
Can't craft Resonant Energy Cells from Thermal Expansion

### ISSUE THREAD

**Issue by DanBTechnology** [TheLimePixel/Crop-Block#19]
Looked up the recipe in JEI and there's nothing there... Tried it doesn't work.

**Comment by TheLimePixel** [comment]
Do you even 1.10.2+ mate? You apply upgrade kits to the regular one.

**Comment by DanBTechnology** [comment]
Oh my bad... I haven't messed around with 1.10.2 TE... Thanks sorry for the trouble!
