### ISSUE TITLE
Barrel Crash

### ISSUE THREAD

**Issue by ZachTGC** [TheLimePixel/Crop-Block#20]
When it rains, oak barrels collect the water. But, the water cap doesn't really work with them when it rains, and the barrels overflow causing a crash

Crash report : The game crashed whilst ticking block entity
The game crashed whilst ticking block entity
Error: java.lang.AssertionError: With 16017mb of total fluid, somehow consumed -1mb, which should be impossible!

**Comment by SilentAssassin01** [comment]
This has been reported before and the mod author knows about it #13 .
