### ISSUE TITLE
Incorrect quest notes for Pumpkin and Nature Seeds

### ISSUE THREAD

**Issue by zeryl** [TheLimePixel/Crop-Block#3]
* Quest states that Carrots and Wheat are cross-bred to get pumpkin, however, JEI shows Carrot and Potato
* Quest states that Sugar Cane and Dirt are cross-bred to get Nature seeds, JEI shows Melon and Dirt

**Comment by TheLimePixel** [comment]
That was already fixed in 1.0.0.1.
