### ISSUE TITLE
Can not craft Flux Crystal Essence

### ISSUE THREAD

**Issue by printerm5n** [TheLimePixel/Crop-Block#30]
There should be a way to convert from the Essence to the Gem so you can farm the Blocks for the Singularity, but it's not listed in the tabs.
![2018-06-14_21 54 02](https://user-images.githubusercontent.com/37993811/41447995-ce20c100-701d-11e8-9de3-58171c970a14.png)

**Comment by TheLimePixel** [comment]
I have no idea why this was closed.
