### ISSUE TITLE
Mushrooms

### ISSUE THREAD

**Issue by Giangiuz** [TheLimePixel/Crop-Block#32]
In SinglePlayer, when I try to breed the carrot with the potato, mushroom doesn't grow.
I worked with a double crow stick in the center on Mycelium.

**Comment by SilentAssassin01** [comment]
The brown and red mushrooms have to be in darkness to grow, white ones however (I'm pretty sure) need to be in a lit up area like other crops.

**Comment by TheLimePixel** [comment]
No, they need to have a lightlevel between 10 and 0, meaning they can't be in complete darkness.
