### ISSUE TITLE
Can't place crop sticks

### ISSUE THREAD

**Issue by ghost** [TheLimePixel/Crop-Block#34]
Hi.
I tried to place crop sticks but I couldn't.
I tried on both farmland and the watered farmland and none worked.
Any suggestions??

**Comment by Kreeate** [comment]
https://github.com/AgriCraft/AgriCraft/pull/1152
Seems to be an issue with Agricraft and latest forge versions.

I've personally reverted back to _forge-14.23.4.2707_  until Agricraft is updated on curseforge.
With _forge-14.23.4.2707_ the crop sticks are working.
Warning : Backup your world before messing around with forge!

For those who don't know how to change your forge version...
1. Press "Play" on the pack in Twitch to start the Minecraft Launcher
2. Press "Edit Profile" 
3. Under "Use version" click the drop-down and select the forge version.
4. Click "Save Profile"
5. Click "Play"

**Comment by ghost** [comment]
Thanks, It worked!
I'll close this now.
