### ISSUE TITLE
Bug involving JEI in latest version

### ISSUE THREAD

**Issue by jl456lj** [TheLimePixel/Crop-Block#36]
Version: 1.3 
Singleplayer or multiplayer: Multiplayer
Issue: Hovering over cobblestone and pressing U (aka seeing the recipes involving cobblestone) causes client side crash. Doesn't matter whether it is on the JEI item catalogue or the crafting recipes. Replicable.

Crash report: https://pastebin.com/PnL418ci

**Comment by ThatGamerBlue** [comment]
fix has been pushed out in 1.3.2 or not?
e: yes

**Comment by Xidik-uk** [comment]
The game crashed whilst updating screen events
Error: java.lang.RuntimeException: Fluid tinker_io.fluids.PureMetal@2df96e5f (puremetal, class tinker_io.fluids.PureMetal) from item 1xic2.fluid_cell@0 returned an unregistered block from getBlock(). This is a major bug in the mod that fluid belongs to.

This is a result of pressing U on cobble (pack version 1.3.3) - I guess it's a conflict between JEI and other mods :(
