### ISSUE TITLE
Server crash loop

### ISSUE THREAD

**Issue by Xidik-uk** [TheLimePixel/Crop-Block#41]
Someone on our server had placed some liquid starlight. They went on to break the block underneath it so the liquid fell into the void.  At this point the server crashed due to to finite water mod. Upon server restart, it crashed again and went into a crash loop.  I disabled the finite water mod and at least the server started up and remains running without finite water mod.

I don't know if it's a config thing or a mod clash with astral sorcery but I thought I should let you know.

**Comment by Xidik-uk** [comment]
P.s. version 1.3 server files / client

**Comment by TheLimePixel** [comment]
Well, a crash log would help.

**Comment by Xidik-uk** [comment]
I knew I'd forgotten something ;)
[crash-2018-08-03_21.24.00-server.txt](https://github.com/EmosewaPixel/Crop-Block/files/2259791/crash-2018-08-03_21.24.00-server.txt)

**Comment by TheLimePixel** [comment]
Huh, I don't get why I wasn't using the mod I usually use for finite fluids. I'm assuming they were in an Ocean biome. By the default the mod lets you have infinite water in oceans, but that's turned off. Guess there's a bug there. Either way, in another update I'll change it to the mod I usually use for handling finite fluids. I would release another one today, but my Internet isn't the best atm, so uploading another server file would take a while. I really wish you told me before releasing the latest version.

**Comment by Xidik-uk** [comment]
I'll try to be quicker in the future but hope there won't be any need :)
