### ISSUE TITLE
Tech Reborn: Pointing Builders' wand towards Quantum Solar Panels crashes the game.

### ISSUE THREAD

**Issue by jl456lj** [TheLimePixel/Crop-Block#44]
Pack Version: 1.3.2
SP or MP: multiplayer server
Issue: Pointing the unbreakable wand (max 64 blocks) towards Quantum Solar Panels causes crash in the Minecraft client. Reproducible in multiplayer only. Have not tested in multiplayer whether other solar panels or other builders' wands will cause the same issue.
Crash report: https://pastebin.com/2EzHHPeW

**Comment by TheLimePixel** [comment]
It's a tile entity. There is nothing that can be done here besides for Better Builder's Wands disallowing you to place them.
