### ISSUE TITLE
JAOPCA Elementium blocks are uncraftable using traditional methods.

### ISSUE THREAD

**Issue by ThatGamerBlue** [TheLimePixel/Crop-Block#45]
9x Elementium Ingots makes 1x Elementium Block from Botania, which cannot be used to create the Elementium singularity. You can convert Botania blocks to JAOPCA blocks using a smeltery (smelt it down into molten, cast into blocks) however this is rather inconvenient when grinding for a singularity.

**Comment by TheLimePixel** [comment]
Yeah, I already fixed this in dev.
