### ISSUE TITLE
Awakened Draconium Crux (dragon heart & inferium essence)

### ISSUE THREAD

**Issue by Ozzymud** [TheLimePixel/Crop-Block#8]
I only have one item left in the quest book, awakened draconium. In order to crossbreed there needs to be a crux under the soil. To make the crux requires a dragon heart. I see no way to get to the end. There is no portal recipe, end cake, artificial end portal, etc that I can see. Also it needs supremium essence, I see no way to get even inferium or the seeds for it. Help?  

Edit: Seems weird as the dragon seeds were T6 and they grew without the dragon crux.

**Comment by TheLimePixel** [comment]
yeah, you don't need cruxes.

**Comment by Ozzymud** [comment]
well.. you wouldn't if the json didnt specify it: 

```
    "conditions": [
      {
        "amount": 1,
        "min_x": 0,
        "min_y": -2,
        "min_z": 0,
        "max_x": 0,
        "max_y": -2,
        "max_z": 0,
        "item": "mysticalagradditions:special",
        "meta": 4,
        "tags": "",
        "ignoreMeta": true,
        "ignoreTags": [],
        "useOreDict": false
      }
    ]
```

Edit: Also, about the essence.. I'm assuming the only way to get them is thru spawning mobs via eggs and killing them?
